# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awls < Formula
  desc "Lookup EC2 information in the terminal"
  homepage ""
  version "0.3.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danpilch/awls/releases/download/v0.3.0/awls_0.3.0_darwin_amd64.tar.gz"
      sha256 "1c0787c11cba9b33967c4c85ff1153180f0ee127a6c20d8313282456cfad5c04"
    end
    if Hardware::CPU.arm?
      url "https://github.com/danpilch/awls/releases/download/v0.3.0/awls_0.3.0_darwin_arm64.tar.gz"
      sha256 "8df2ce7fd4e1d1dcfda44ac0a50c595a2eb826e174ad7bf37b76bd2589cdcafd"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/danpilch/awls/releases/download/v0.3.0/awls_0.3.0_linux_amd64.tar.gz"
      sha256 "215e714391a04d49ba871199349d7302743e2f50477e6eaf222d2c032ac3e7b9"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danpilch/awls/releases/download/v0.3.0/awls_0.3.0_linux_arm64.tar.gz"
      sha256 "97481dc490758f436d46d17c710692a3a04d06378477f20b3ecea15fd1fedda1"
    end
  end

  def install
    bin.install "awls"
  end
end
