# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awls < Formula
  desc "Lookup EC2 information in the terminal"
  homepage ""
  version "0.2.3"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/danpilch/awls/releases/download/v0.2.3/awls_0.2.3_darwin_amd64.tar.gz"
    sha256 "ffd79183f238ff72ce43eb810897db9a77db76df3db1e51956988bfbd51ff583"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/danpilch/awls/releases/download/v0.2.3/awls_0.2.3_darwin_arm64.tar.gz"
    sha256 "4de45dd2aedc2844826d08fc8c241cb129ac0c6730eadfc34a4c2dedf6f831d7"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/danpilch/awls/releases/download/v0.2.3/awls_0.2.3_linux_amd64.tar.gz"
    sha256 "0a8ae0316266cdf4c94cf6eef7716c7fa877ca43b70acb969030093df4a8f507"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/danpilch/awls/releases/download/v0.2.3/awls_0.2.3_linux_arm64.tar.gz"
    sha256 "f2694706f4cfe735c23a18935e2133139bf6c1e3d2880dee55db9d80539df07b"
  end

  def install
    bin.install "awls"
  end
end
