# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProbateSearch < Formula
  desc "Alert on probate record searches"
  homepage ""
  version "0.1.1"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danpilch/probate-search/releases/download/v0.1.1/probate-search_0.1.1_darwin_amd64.tar.gz"
      sha256 "2e3b6372466b3aa0a4593614a2daac44877298f5e83322acba5b61b9f2dba9b2"
    end
    if Hardware::CPU.arm?
      url "https://github.com/danpilch/probate-search/releases/download/v0.1.1/probate-search_0.1.1_darwin_arm64.tar.gz"
      sha256 "13888b174420c362c06068569b852d94844b213de6ec4746e0f55f15b9cbc021"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/danpilch/probate-search/releases/download/v0.1.1/probate-search_0.1.1_linux_amd64.tar.gz"
      sha256 "d94eacaaf591cf9551f46f256207a0ac1eb206aed3733c93739780086bec3a90"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danpilch/probate-search/releases/download/v0.1.1/probate-search_0.1.1_linux_arm64.tar.gz"
      sha256 "80013234de1dbf5b1bc91fdd3b8a2c8d27e968dba3c01d77d0ef9b027b1236ca"
    end
  end

  def install
    bin.install "probate-search"
  end
end
