# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProbateSearch < Formula
  desc "Alert on probate record searches"
  homepage ""
  version "0.1.3"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danpilch/probate-search/releases/download/v0.1.3/probate-search_0.1.3_darwin_amd64.tar.gz"
      sha256 "0888fd9c770975bbfcd8deaf1591c7d4ec6be1a6e7d4d2a195e23a34408570a1"
    end
    if Hardware::CPU.arm?
      url "https://github.com/danpilch/probate-search/releases/download/v0.1.3/probate-search_0.1.3_darwin_arm64.tar.gz"
      sha256 "c03765ea4f00cbf321608dd0b20c20cf61e8e1ff7f9c1edb7b9f033e5e6fdf67"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/danpilch/probate-search/releases/download/v0.1.3/probate-search_0.1.3_linux_amd64.tar.gz"
      sha256 "f874a684a1260708c0fe6b56844e6d3a8d93c6ce5e1dc8fdbc54caa54f2648ae"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danpilch/probate-search/releases/download/v0.1.3/probate-search_0.1.3_linux_arm64.tar.gz"
      sha256 "ce9374392dfecec2bd2bf3438ec9d04dfc2ba6863ebf7470d9e3f53fe448e40b"
    end
  end

  def install
    bin.install "probate-search"
  end
end
